# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Option.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 60, 121, 523))
        self.gridLayoutWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_usename_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_usename_4.setEnabled(False)
        self.toolButton_usename_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/warning_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_usename_4.setIcon(icon)
        self.toolButton_usename_4.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_usename_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_usename_4.setAutoRaise(False)
        self.toolButton_usename_4.setObjectName("toolButton_usename_4")
        self.gridLayout.addWidget(self.toolButton_usename_4, 3, 0, 1, 1)
        self.toolButton_usename_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_usename_2.setEnabled(False)
        self.toolButton_usename_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_usename_2.setIcon(icon1)
        self.toolButton_usename_2.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_usename_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_usename_2.setAutoRaise(False)
        self.toolButton_usename_2.setObjectName("toolButton_usename_2")
        self.gridLayout.addWidget(self.toolButton_usename_2, 2, 0, 1, 1)
        self.toolButton_usename_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_usename_3.setEnabled(False)
        self.toolButton_usename_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/laptop_serialport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_usename_3.setIcon(icon2)
        self.toolButton_usename_3.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_usename_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_usename_3.setAutoRaise(False)
        self.toolButton_usename_3.setObjectName("toolButton_usename_3")
        self.gridLayout.addWidget(self.toolButton_usename_3, 4, 0, 1, 1)
        self.toolButton_usename = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_usename.setEnabled(False)
        self.toolButton_usename.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/user625.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_usename.setIcon(icon3)
        self.toolButton_usename.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_usename.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_usename.setAutoRaise(False)
        self.toolButton_usename.setObjectName("toolButton_usename")
        self.gridLayout.addWidget(self.toolButton_usename, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(240, 150, 481, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_showoption = QtWidgets.QLabel(self.centralwidget)
        self.label_showoption.setEnabled(False)
        self.label_showoption.setGeometry(QtCore.QRect(180, 50, 555, 122))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_showoption.setFont(font)
        self.label_showoption.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_showoption.setMidLineWidth(1)
        self.label_showoption.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showoption.setOpenExternalLinks(False)
        self.label_showoption.setObjectName("label_showoption")
        self.pushButton_gotologin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gotologin.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.pushButton_gotologin.setObjectName("pushButton_gotologin")
        self.pushButton_gotoregister = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gotoregister.setGeometry(QtCore.QRect(100, 0, 93, 28))
        self.pushButton_gotoregister.setObjectName("pushButton_gotoregister")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 60, 541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(203, 70, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(210, 570, 541, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(740, 70, 16, 511))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(210, 140, 541, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_usename_4.setText(_translate("MainWindow", "虚假举报"))
        self.toolButton_usename_2.setText(_translate("MainWindow", "查询物流"))
        self.toolButton_usename_3.setText(_translate("MainWindow", "问题反馈"))
        self.toolButton_usename.setText(_translate("MainWindow", "账户名称"))
        self.label_showoption.setText(_translate("MainWindow", "功能选项"))
        self.pushButton_gotologin.setText(_translate("MainWindow", "用户登录"))
        self.pushButton_gotoregister.setText(_translate("MainWindow", "用户注册"))

import agv_icon_rc
